import React, { useState } from 'react';
import FAQ from './FAQ';
import './FAQ.css';

function Allfaq () {
  const [faqs, setfaqs] = useState([
    {
      question: '1. Who is B₹OSE ?',
      answer: 'B₹OSE is an organisation which provides various Financial solution'+
       'to its Client(Portfolio management/Advisory/calls/Investment consultancy) and Learning program & Webinars to Budding traders.',
      open: true
    },
    {
      question: '2. Where is it based ?',
      answer: 'B₹OSE is based in Patna, Bihar, IN.' +
      'It has clients of different states like Jharkhand, Assam, Bihar, UP.',
      open: false
    },
    {
      question: '3. How can you join us for Portfolio management ?',
      answer: '- You have to provide ID & Password of your Dmat account.'+
      ' We donot ask for any other details. You donot need to do any paperwork in related to this.',
      open: false
    },
    {
      question: '4. What are the charges for portfolio management ?',
      answer: '- We have two schemes for charges a.I will charge 25% of net profit'
      + '( 25-75 rule) only and rest 75% will be yours and no charge on total capital, etc. Here I will not be bearing'
      +' downside risk.b. I will be paying you 15% annually with full downside risk cover . In'
      +'this scheme I will take my profit share at the end of every quarter.'
      +'Example If I make 20% in a quarter then I will take 16% of the profit and rest 4% will be yours. In that way your target of'
      +'15% will be completed in 4 quarters. In exception case, If I make less than 4% or loss in a quarter then I will pay you so'
      +'that target of 4% per quarter can be achieved.',
        open: false
    },{
      question: '5. What is the minimmum amount from which You can start ?',
      answer: 'Minimum capital(Testing capital) from which you can start is 1,00,000/ If you do not want to continue after testing period then the profits generated by this capital within testing period(6 months) will also be distributed as 25 - 75 rule or 8% will be given to you if you have chose 2nd scheme.,',
      open: false
    },
    {
      question: '6. What is the minimmum holding period/Locking period ?',
      answer: 'Locking period of capital is for 1 year . In that period if I am either making profit or not you will not be allowed to go.'
      +'Sometime trader do not make money in first 10 months and in last 2 months due to certain market situations they make'
      +'sufficient amt. of money. That’s why you’re advised to test for at least 1 year.',
      open: false
    },
    {
      question:'7. Do you need to transfer funds to our account ?',
      answer:'No, You don'+'t need to transfer your capital to our account. you just need to share your Dmat account Login detail.',
      open: false
    },
    {
      question:'8. Can you do SIP/Monthly commintment after joining us ?',
      answer:'- Yes, You can do SIP or Monthly addition of funds in your account. As we generally suggest our Clients to do Monthly/Quarterly addition of funds in their account.',
      open: false 
    },
    {
      question:'9. What are the Average expected CAGR ?',
      answer:'- I do not want to make any commitment related to returns on investment but my past record shows 3-5% per month. which equates to 35- 60% CAGR. Which is 4 5 times what any govt. FD pays.',
      open: false 
    },
    {
      question:'10. When and How will we charging ?',
      answer:'- I will be taking my 25% share in profit at the end of every 6 months for your 1st & 2nd year and from 3rd year onwards I will'
      +'be taking profit share annually.',
      open: false 
    },
    {
      question:'11. How can you get mentored ?',
      answer:'- As of now we run a detailed discussion group on whatapp. Weekly webinars are held on every Sat/Sun. These Webinars include either topic on current situation of Market or on a particuar topic. Mentor deal with every query of members.',
      open: false 
    },
    {
      question:'12. What are the charges of Mentoring ?',
      answer:'- There is very basic fee of mentoring of ₹500 per head per month.',
      open: false 
    },
    {
      question:'13. What are the charges of joining Live Calls & Discussion group ?',
      answer:'- There is very basic fee of  of Live Calls & Discussion group is ₹200 per head per month.',
      open: false 
    },
    {
      question:'14. How can you get live trading session ?',
      answer:'- We are launching our live trading program. Candidates will have to join to mentor via link. That will help budding traders to have a real experience of how professionals trade. It will be held on 3-4 days a week.',
      open: false 
    },
    {
      question:'15. What are the charges of Live trading Program ?',
      answer:'There is very basic fee of Live trading session of ₹300 per head per month.',
      open: false 
    },
    {
      question:'16. Is investment Risky ?',
      answer:'- Yes. It is risk. It has to be. If you are seeking risk free investment, Go with FD and wait 12 years for your 100% return on capital without risk.'
      +'Here we are trying to generate 100% return much faster. This reward demands some risk to be volunteered. Inorder to reach faster, you need to accelerate and volunteer a risk.',
      open: false 
    },
    {
      question:'17. Why should I Give my Portfoio to BROSE ?',
      answer:'- To start with, Your are not the “customer” for BROSE.'
      +'Let us explain, For a company they have 3 major participants in its success.'
      +'1. Customer2. Investor/Partner 3. Employees/Colleagues',
      open: false 
    }
  ]);

  const toggleFAQ = index => {
    setfaqs(faqs.map((faq, i) => {
      if (i === index) {
        faq.open = !faq.open
      } else {
        faq.open = false;
      }

      return faq;
    }))
  }


  return (
    <div className="App">
      <header><h1>FAQ (Frequently asked question)</h1></header>
      <div className="faqs">
        {faqs.map((faq, i) => (
          <FAQ faq={faq} index={i} toggleFAQ={toggleFAQ} />
        ))}
      </div>
    </div>
  );
}

export default Allfaq;